// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_common.proto

#ifndef PROTOBUF_message_5fcommon_2eproto__INCLUDED
#define PROTOBUF_message_5fcommon_2eproto__INCLUDED

#include "../defines.h"
#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace rpc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_message_5fcommon_2eproto();
void protobuf_AssignDesc_message_5fcommon_2eproto();
void protobuf_ShutdownFile_message_5fcommon_2eproto();

class WorkGroupInfo;

enum Filter {
  EXISTING_ONLY = 0,
  DELETED_ONLY = 1,
  ALL_ENTRIES = 2
};
bool Filter_IsValid(int value);
const Filter Filter_MIN = EXISTING_ONLY;
const Filter Filter_MAX = ALL_ENTRIES;
const int Filter_ARRAYSIZE = Filter_MAX + 1;

const ::google::protobuf::EnumDescriptor* Filter_descriptor();
inline const ::std::string& Filter_Name(Filter value) {
  return ::google::protobuf::internal::NameOfEnum(
    Filter_descriptor(), value);
}
inline bool Filter_Parse(
    const ::std::string& name, Filter* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Filter>(
    Filter_descriptor(), name, value);
}
// ===================================================================

class WorkGroupInfo : public ::google::protobuf::Message {
 public:
  WorkGroupInfo();
  virtual ~WorkGroupInfo();

  WorkGroupInfo(const WorkGroupInfo& from);

  inline WorkGroupInfo& operator=(const WorkGroupInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorkGroupInfo& default_instance();

  void Swap(WorkGroupInfo* other);

  // implements Message ----------------------------------------------

  WorkGroupInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorkGroupInfo& from);
  void MergeFrom(const WorkGroupInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 workgroup_id = 1;
  inline bool has_workgroup_id() const;
  inline void clear_workgroup_id();
  static const int kWorkgroupIdFieldNumber = 1;
  inline ::google::protobuf::int64 workgroup_id() const;
  inline void set_workgroup_id(::google::protobuf::int64 value);

  // optional string workgroup_name = 2;
  inline bool has_workgroup_name() const;
  inline void clear_workgroup_name();
  static const int kWorkgroupNameFieldNumber = 2;
  inline const ::std::string& workgroup_name() const;
  inline void set_workgroup_name(const ::std::string& value);
  inline void set_workgroup_name(const char* value);
  inline void set_workgroup_name(const char* value, size_t size);
  inline ::std::string* mutable_workgroup_name();
  inline ::std::string* release_workgroup_name();
  inline void set_allocated_workgroup_name(::std::string* workgroup_name);

  // optional string description = 3;
  inline bool has_description() const;
  inline void clear_description();
  static const int kDescriptionFieldNumber = 3;
  inline const ::std::string& description() const;
  inline void set_description(const ::std::string& value);
  inline void set_description(const char* value);
  inline void set_description(const char* value, size_t size);
  inline ::std::string* mutable_description();
  inline ::std::string* release_description();
  inline void set_allocated_description(::std::string* description);

  // optional string creator_login = 4;
  inline bool has_creator_login() const;
  inline void clear_creator_login();
  static const int kCreatorLoginFieldNumber = 4;
  inline const ::std::string& creator_login() const;
  inline void set_creator_login(const ::std::string& value);
  inline void set_creator_login(const char* value);
  inline void set_creator_login(const char* value, size_t size);
  inline ::std::string* mutable_creator_login();
  inline ::std::string* release_creator_login();
  inline void set_allocated_creator_login(::std::string* creator_login);

  // optional int64 access_mode = 5;
  inline bool has_access_mode() const;
  inline void clear_access_mode();
  static const int kAccessModeFieldNumber = 5;
  inline ::google::protobuf::int64 access_mode() const;
  inline void set_access_mode(::google::protobuf::int64 value);

  // optional bool invite_accepted = 8;
  inline bool has_invite_accepted() const;
  inline void clear_invite_accepted();
  static const int kInviteAcceptedFieldNumber = 8;
  inline bool invite_accepted() const;
  inline void set_invite_accepted(bool value);

  // optional string key = 9;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 9;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const char* value, size_t size);
  inline ::std::string* mutable_key();
  inline ::std::string* release_key();
  inline void set_allocated_key(::std::string* key);

  // optional string key_signature = 10;
  inline bool has_key_signature() const;
  inline void clear_key_signature();
  static const int kKeySignatureFieldNumber = 10;
  inline const ::std::string& key_signature() const;
  inline void set_key_signature(const ::std::string& value);
  inline void set_key_signature(const char* value);
  inline void set_key_signature(const char* value, size_t size);
  inline ::std::string* mutable_key_signature();
  inline ::std::string* release_key_signature();
  inline void set_allocated_key_signature(::std::string* key_signature);

  // optional string key_salt = 11;
  inline bool has_key_salt() const;
  inline void clear_key_salt();
  static const int kKeySaltFieldNumber = 11;
  inline const ::std::string& key_salt() const;
  inline void set_key_salt(const ::std::string& value);
  inline void set_key_salt(const char* value);
  inline void set_key_salt(const char* value, size_t size);
  inline ::std::string* mutable_key_salt();
  inline ::std::string* release_key_salt();
  inline void set_allocated_key_salt(::std::string* key_salt);

  // optional int32 encryption_algo = 12;
  inline bool has_encryption_algo() const;
  inline void clear_encryption_algo();
  static const int kEncryptionAlgoFieldNumber = 12;
  inline ::google::protobuf::int32 encryption_algo() const;
  inline void set_encryption_algo(::google::protobuf::int32 value);

  // optional int32 encryption_type = 13;
  inline bool has_encryption_type() const;
  inline void clear_encryption_type();
  static const int kEncryptionTypeFieldNumber = 13;
  inline ::google::protobuf::int32 encryption_type() const;
  inline void set_encryption_type(::google::protobuf::int32 value);

  // optional int64 size = 16;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 16;
  inline ::google::protobuf::int64 size() const;
  inline void set_size(::google::protobuf::int64 value);

  // optional int64 creation_date = 17;
  inline bool has_creation_date() const;
  inline void clear_creation_date();
  static const int kCreationDateFieldNumber = 17;
  inline ::google::protobuf::int64 creation_date() const;
  inline void set_creation_date(::google::protobuf::int64 value);

  // optional int64 deletion_date = 18;
  inline bool has_deletion_date() const;
  inline void clear_deletion_date();
  static const int kDeletionDateFieldNumber = 18;
  inline ::google::protobuf::int64 deletion_date() const;
  inline void set_deletion_date(::google::protobuf::int64 value);

  // optional string creation_date_str = 19;
  inline bool has_creation_date_str() const;
  inline void clear_creation_date_str();
  static const int kCreationDateStrFieldNumber = 19;
  inline const ::std::string& creation_date_str() const;
  inline void set_creation_date_str(const ::std::string& value);
  inline void set_creation_date_str(const char* value);
  inline void set_creation_date_str(const char* value, size_t size);
  inline ::std::string* mutable_creation_date_str();
  inline ::std::string* release_creation_date_str();
  inline void set_allocated_creation_date_str(::std::string* creation_date_str);

  // optional string deletion_date_str = 20;
  inline bool has_deletion_date_str() const;
  inline void clear_deletion_date_str();
  static const int kDeletionDateStrFieldNumber = 20;
  inline const ::std::string& deletion_date_str() const;
  inline void set_deletion_date_str(const ::std::string& value);
  inline void set_deletion_date_str(const char* value);
  inline void set_deletion_date_str(const char* value, size_t size);
  inline ::std::string* mutable_deletion_date_str();
  inline ::std::string* release_deletion_date_str();
  inline void set_allocated_deletion_date_str(::std::string* deletion_date_str);

  // optional bool is_deleted = 23;
  inline bool has_is_deleted() const;
  inline void clear_is_deleted();
  static const int kIsDeletedFieldNumber = 23;
  inline bool is_deleted() const;
  inline void set_is_deleted(bool value);

  // optional int64 company_id = 24;
  inline bool has_company_id() const;
  inline void clear_company_id();
  static const int kCompanyIdFieldNumber = 24;
  inline ::google::protobuf::int64 company_id() const;
  inline void set_company_id(::google::protobuf::int64 value);

  // optional int32 workgroup_type = 25;
  inline bool has_workgroup_type() const;
  inline void clear_workgroup_type();
  static const int kWorkgroupTypeFieldNumber = 25;
  inline ::google::protobuf::int32 workgroup_type() const;
  inline void set_workgroup_type(::google::protobuf::int32 value);

  // optional string workgroup_metadata = 26;
  inline bool has_workgroup_metadata() const;
  inline void clear_workgroup_metadata();
  static const int kWorkgroupMetadataFieldNumber = 26;
  inline const ::std::string& workgroup_metadata() const;
  inline void set_workgroup_metadata(const ::std::string& value);
  inline void set_workgroup_metadata(const char* value);
  inline void set_workgroup_metadata(const char* value, size_t size);
  inline ::std::string* mutable_workgroup_metadata();
  inline ::std::string* release_workgroup_metadata();
  inline void set_allocated_workgroup_metadata(::std::string* workgroup_metadata);

  // optional int64 files_count = 27;
  inline bool has_files_count() const;
  inline void clear_files_count();
  static const int kFilesCountFieldNumber = 27;
  inline ::google::protobuf::int64 files_count() const;
  inline void set_files_count(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:rpc.WorkGroupInfo)
 private:
  inline void set_has_workgroup_id();
  inline void clear_has_workgroup_id();
  inline void set_has_workgroup_name();
  inline void clear_has_workgroup_name();
  inline void set_has_description();
  inline void clear_has_description();
  inline void set_has_creator_login();
  inline void clear_has_creator_login();
  inline void set_has_access_mode();
  inline void clear_has_access_mode();
  inline void set_has_invite_accepted();
  inline void clear_has_invite_accepted();
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_key_signature();
  inline void clear_has_key_signature();
  inline void set_has_key_salt();
  inline void clear_has_key_salt();
  inline void set_has_encryption_algo();
  inline void clear_has_encryption_algo();
  inline void set_has_encryption_type();
  inline void clear_has_encryption_type();
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_creation_date();
  inline void clear_has_creation_date();
  inline void set_has_deletion_date();
  inline void clear_has_deletion_date();
  inline void set_has_creation_date_str();
  inline void clear_has_creation_date_str();
  inline void set_has_deletion_date_str();
  inline void clear_has_deletion_date_str();
  inline void set_has_is_deleted();
  inline void clear_has_is_deleted();
  inline void set_has_company_id();
  inline void clear_has_company_id();
  inline void set_has_workgroup_type();
  inline void clear_has_workgroup_type();
  inline void set_has_workgroup_metadata();
  inline void clear_has_workgroup_metadata();
  inline void set_has_files_count();
  inline void clear_has_files_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 workgroup_id_;
  ::std::string* workgroup_name_;
  ::std::string* description_;
  ::std::string* creator_login_;
  ::google::protobuf::int64 access_mode_;
  ::std::string* key_;
  ::std::string* key_signature_;
  ::std::string* key_salt_;
  ::google::protobuf::int32 encryption_algo_;
  ::google::protobuf::int32 encryption_type_;
  ::google::protobuf::int64 size_;
  ::google::protobuf::int64 creation_date_;
  ::google::protobuf::int64 deletion_date_;
  bool invite_accepted_;
  bool is_deleted_;
  ::google::protobuf::int32 workgroup_type_;
  ::std::string* creation_date_str_;
  ::std::string* deletion_date_str_;
  ::google::protobuf::int64 company_id_;
  ::std::string* workgroup_metadata_;
  ::google::protobuf::int64 files_count_;
  friend void  protobuf_AddDesc_message_5fcommon_2eproto();
  friend void protobuf_AssignDesc_message_5fcommon_2eproto();
  friend void protobuf_ShutdownFile_message_5fcommon_2eproto();

  void InitAsDefaultInstance();
  static WorkGroupInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// WorkGroupInfo

// optional int64 workgroup_id = 1;
inline bool WorkGroupInfo::has_workgroup_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorkGroupInfo::set_has_workgroup_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorkGroupInfo::clear_has_workgroup_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorkGroupInfo::clear_workgroup_id() {
  workgroup_id_ = GOOGLE_LONGLONG(0);
  clear_has_workgroup_id();
}
inline ::google::protobuf::int64 WorkGroupInfo::workgroup_id() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.workgroup_id)
  return workgroup_id_;
}
inline void WorkGroupInfo::set_workgroup_id(::google::protobuf::int64 value) {
  set_has_workgroup_id();
  workgroup_id_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.workgroup_id)
}

// optional string workgroup_name = 2;
inline bool WorkGroupInfo::has_workgroup_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WorkGroupInfo::set_has_workgroup_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WorkGroupInfo::clear_has_workgroup_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WorkGroupInfo::clear_workgroup_name() {
  if (workgroup_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_name_->clear();
  }
  clear_has_workgroup_name();
}
inline const ::std::string& WorkGroupInfo::workgroup_name() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.workgroup_name)
  return *workgroup_name_;
}
inline void WorkGroupInfo::set_workgroup_name(const ::std::string& value) {
  set_has_workgroup_name();
  if (workgroup_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_name_ = new ::std::string;
  }
  workgroup_name_->assign(value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.workgroup_name)
}
inline void WorkGroupInfo::set_workgroup_name(const char* value) {
  set_has_workgroup_name();
  if (workgroup_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_name_ = new ::std::string;
  }
  workgroup_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupInfo.workgroup_name)
}
inline void WorkGroupInfo::set_workgroup_name(const char* value, size_t size) {
  set_has_workgroup_name();
  if (workgroup_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_name_ = new ::std::string;
  }
  workgroup_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupInfo.workgroup_name)
}
inline ::std::string* WorkGroupInfo::mutable_workgroup_name() {
  set_has_workgroup_name();
  if (workgroup_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupInfo.workgroup_name)
  return workgroup_name_;
}
inline ::std::string* WorkGroupInfo::release_workgroup_name() {
  clear_has_workgroup_name();
  if (workgroup_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = workgroup_name_;
    workgroup_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WorkGroupInfo::set_allocated_workgroup_name(::std::string* workgroup_name) {
  if (workgroup_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete workgroup_name_;
  }
  if (workgroup_name) {
    set_has_workgroup_name();
    workgroup_name_ = workgroup_name;
  } else {
    clear_has_workgroup_name();
    workgroup_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupInfo.workgroup_name)
}

// optional string description = 3;
inline bool WorkGroupInfo::has_description() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WorkGroupInfo::set_has_description() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WorkGroupInfo::clear_has_description() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WorkGroupInfo::clear_description() {
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_->clear();
  }
  clear_has_description();
}
inline const ::std::string& WorkGroupInfo::description() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.description)
  return *description_;
}
inline void WorkGroupInfo::set_description(const ::std::string& value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.description)
}
inline void WorkGroupInfo::set_description(const char* value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(value);
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupInfo.description)
}
inline void WorkGroupInfo::set_description(const char* value, size_t size) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupInfo.description)
}
inline ::std::string* WorkGroupInfo::mutable_description() {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupInfo.description)
  return description_;
}
inline ::std::string* WorkGroupInfo::release_description() {
  clear_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = description_;
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WorkGroupInfo::set_allocated_description(::std::string* description) {
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete description_;
  }
  if (description) {
    set_has_description();
    description_ = description;
  } else {
    clear_has_description();
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupInfo.description)
}

// optional string creator_login = 4;
inline bool WorkGroupInfo::has_creator_login() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void WorkGroupInfo::set_has_creator_login() {
  _has_bits_[0] |= 0x00000008u;
}
inline void WorkGroupInfo::clear_has_creator_login() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void WorkGroupInfo::clear_creator_login() {
  if (creator_login_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creator_login_->clear();
  }
  clear_has_creator_login();
}
inline const ::std::string& WorkGroupInfo::creator_login() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.creator_login)
  return *creator_login_;
}
inline void WorkGroupInfo::set_creator_login(const ::std::string& value) {
  set_has_creator_login();
  if (creator_login_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creator_login_ = new ::std::string;
  }
  creator_login_->assign(value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.creator_login)
}
inline void WorkGroupInfo::set_creator_login(const char* value) {
  set_has_creator_login();
  if (creator_login_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creator_login_ = new ::std::string;
  }
  creator_login_->assign(value);
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupInfo.creator_login)
}
inline void WorkGroupInfo::set_creator_login(const char* value, size_t size) {
  set_has_creator_login();
  if (creator_login_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creator_login_ = new ::std::string;
  }
  creator_login_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupInfo.creator_login)
}
inline ::std::string* WorkGroupInfo::mutable_creator_login() {
  set_has_creator_login();
  if (creator_login_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creator_login_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupInfo.creator_login)
  return creator_login_;
}
inline ::std::string* WorkGroupInfo::release_creator_login() {
  clear_has_creator_login();
  if (creator_login_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = creator_login_;
    creator_login_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WorkGroupInfo::set_allocated_creator_login(::std::string* creator_login) {
  if (creator_login_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete creator_login_;
  }
  if (creator_login) {
    set_has_creator_login();
    creator_login_ = creator_login;
  } else {
    clear_has_creator_login();
    creator_login_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupInfo.creator_login)
}

// optional int64 access_mode = 5;
inline bool WorkGroupInfo::has_access_mode() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void WorkGroupInfo::set_has_access_mode() {
  _has_bits_[0] |= 0x00000010u;
}
inline void WorkGroupInfo::clear_has_access_mode() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void WorkGroupInfo::clear_access_mode() {
  access_mode_ = GOOGLE_LONGLONG(0);
  clear_has_access_mode();
}
inline ::google::protobuf::int64 WorkGroupInfo::access_mode() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.access_mode)
  return access_mode_;
}
inline void WorkGroupInfo::set_access_mode(::google::protobuf::int64 value) {
  set_has_access_mode();
  access_mode_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.access_mode)
}

// optional bool invite_accepted = 8;
inline bool WorkGroupInfo::has_invite_accepted() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void WorkGroupInfo::set_has_invite_accepted() {
  _has_bits_[0] |= 0x00000020u;
}
inline void WorkGroupInfo::clear_has_invite_accepted() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void WorkGroupInfo::clear_invite_accepted() {
  invite_accepted_ = false;
  clear_has_invite_accepted();
}
inline bool WorkGroupInfo::invite_accepted() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.invite_accepted)
  return invite_accepted_;
}
inline void WorkGroupInfo::set_invite_accepted(bool value) {
  set_has_invite_accepted();
  invite_accepted_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.invite_accepted)
}

// optional string key = 9;
inline bool WorkGroupInfo::has_key() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void WorkGroupInfo::set_has_key() {
  _has_bits_[0] |= 0x00000040u;
}
inline void WorkGroupInfo::clear_has_key() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void WorkGroupInfo::clear_key() {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& WorkGroupInfo::key() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.key)
  return *key_;
}
inline void WorkGroupInfo::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  key_->assign(value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.key)
}
inline void WorkGroupInfo::set_key(const char* value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  key_->assign(value);
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupInfo.key)
}
inline void WorkGroupInfo::set_key(const char* value, size_t size) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupInfo.key)
}
inline ::std::string* WorkGroupInfo::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupInfo.key)
  return key_;
}
inline ::std::string* WorkGroupInfo::release_key() {
  clear_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WorkGroupInfo::set_allocated_key(::std::string* key) {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_;
  }
  if (key) {
    set_has_key();
    key_ = key;
  } else {
    clear_has_key();
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupInfo.key)
}

// optional string key_signature = 10;
inline bool WorkGroupInfo::has_key_signature() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void WorkGroupInfo::set_has_key_signature() {
  _has_bits_[0] |= 0x00000080u;
}
inline void WorkGroupInfo::clear_has_key_signature() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void WorkGroupInfo::clear_key_signature() {
  if (key_signature_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_signature_->clear();
  }
  clear_has_key_signature();
}
inline const ::std::string& WorkGroupInfo::key_signature() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.key_signature)
  return *key_signature_;
}
inline void WorkGroupInfo::set_key_signature(const ::std::string& value) {
  set_has_key_signature();
  if (key_signature_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_signature_ = new ::std::string;
  }
  key_signature_->assign(value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.key_signature)
}
inline void WorkGroupInfo::set_key_signature(const char* value) {
  set_has_key_signature();
  if (key_signature_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_signature_ = new ::std::string;
  }
  key_signature_->assign(value);
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupInfo.key_signature)
}
inline void WorkGroupInfo::set_key_signature(const char* value, size_t size) {
  set_has_key_signature();
  if (key_signature_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_signature_ = new ::std::string;
  }
  key_signature_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupInfo.key_signature)
}
inline ::std::string* WorkGroupInfo::mutable_key_signature() {
  set_has_key_signature();
  if (key_signature_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_signature_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupInfo.key_signature)
  return key_signature_;
}
inline ::std::string* WorkGroupInfo::release_key_signature() {
  clear_has_key_signature();
  if (key_signature_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = key_signature_;
    key_signature_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WorkGroupInfo::set_allocated_key_signature(::std::string* key_signature) {
  if (key_signature_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_signature_;
  }
  if (key_signature) {
    set_has_key_signature();
    key_signature_ = key_signature;
  } else {
    clear_has_key_signature();
    key_signature_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupInfo.key_signature)
}

// optional string key_salt = 11;
inline bool WorkGroupInfo::has_key_salt() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void WorkGroupInfo::set_has_key_salt() {
  _has_bits_[0] |= 0x00000100u;
}
inline void WorkGroupInfo::clear_has_key_salt() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void WorkGroupInfo::clear_key_salt() {
  if (key_salt_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_salt_->clear();
  }
  clear_has_key_salt();
}
inline const ::std::string& WorkGroupInfo::key_salt() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.key_salt)
  return *key_salt_;
}
inline void WorkGroupInfo::set_key_salt(const ::std::string& value) {
  set_has_key_salt();
  if (key_salt_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_salt_ = new ::std::string;
  }
  key_salt_->assign(value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.key_salt)
}
inline void WorkGroupInfo::set_key_salt(const char* value) {
  set_has_key_salt();
  if (key_salt_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_salt_ = new ::std::string;
  }
  key_salt_->assign(value);
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupInfo.key_salt)
}
inline void WorkGroupInfo::set_key_salt(const char* value, size_t size) {
  set_has_key_salt();
  if (key_salt_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_salt_ = new ::std::string;
  }
  key_salt_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupInfo.key_salt)
}
inline ::std::string* WorkGroupInfo::mutable_key_salt() {
  set_has_key_salt();
  if (key_salt_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_salt_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupInfo.key_salt)
  return key_salt_;
}
inline ::std::string* WorkGroupInfo::release_key_salt() {
  clear_has_key_salt();
  if (key_salt_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = key_salt_;
    key_salt_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WorkGroupInfo::set_allocated_key_salt(::std::string* key_salt) {
  if (key_salt_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_salt_;
  }
  if (key_salt) {
    set_has_key_salt();
    key_salt_ = key_salt;
  } else {
    clear_has_key_salt();
    key_salt_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupInfo.key_salt)
}

// optional int32 encryption_algo = 12;
inline bool WorkGroupInfo::has_encryption_algo() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void WorkGroupInfo::set_has_encryption_algo() {
  _has_bits_[0] |= 0x00000200u;
}
inline void WorkGroupInfo::clear_has_encryption_algo() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void WorkGroupInfo::clear_encryption_algo() {
  encryption_algo_ = 0;
  clear_has_encryption_algo();
}
inline ::google::protobuf::int32 WorkGroupInfo::encryption_algo() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.encryption_algo)
  return encryption_algo_;
}
inline void WorkGroupInfo::set_encryption_algo(::google::protobuf::int32 value) {
  set_has_encryption_algo();
  encryption_algo_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.encryption_algo)
}

// optional int32 encryption_type = 13;
inline bool WorkGroupInfo::has_encryption_type() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void WorkGroupInfo::set_has_encryption_type() {
  _has_bits_[0] |= 0x00000400u;
}
inline void WorkGroupInfo::clear_has_encryption_type() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void WorkGroupInfo::clear_encryption_type() {
  encryption_type_ = 0;
  clear_has_encryption_type();
}
inline ::google::protobuf::int32 WorkGroupInfo::encryption_type() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.encryption_type)
  return encryption_type_;
}
inline void WorkGroupInfo::set_encryption_type(::google::protobuf::int32 value) {
  set_has_encryption_type();
  encryption_type_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.encryption_type)
}

// optional int64 size = 16;
inline bool WorkGroupInfo::has_size() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void WorkGroupInfo::set_has_size() {
  _has_bits_[0] |= 0x00000800u;
}
inline void WorkGroupInfo::clear_has_size() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void WorkGroupInfo::clear_size() {
  size_ = GOOGLE_LONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::int64 WorkGroupInfo::size() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.size)
  return size_;
}
inline void WorkGroupInfo::set_size(::google::protobuf::int64 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.size)
}

// optional int64 creation_date = 17;
inline bool WorkGroupInfo::has_creation_date() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void WorkGroupInfo::set_has_creation_date() {
  _has_bits_[0] |= 0x00001000u;
}
inline void WorkGroupInfo::clear_has_creation_date() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void WorkGroupInfo::clear_creation_date() {
  creation_date_ = GOOGLE_LONGLONG(0);
  clear_has_creation_date();
}
inline ::google::protobuf::int64 WorkGroupInfo::creation_date() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.creation_date)
  return creation_date_;
}
inline void WorkGroupInfo::set_creation_date(::google::protobuf::int64 value) {
  set_has_creation_date();
  creation_date_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.creation_date)
}

// optional int64 deletion_date = 18;
inline bool WorkGroupInfo::has_deletion_date() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void WorkGroupInfo::set_has_deletion_date() {
  _has_bits_[0] |= 0x00002000u;
}
inline void WorkGroupInfo::clear_has_deletion_date() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void WorkGroupInfo::clear_deletion_date() {
  deletion_date_ = GOOGLE_LONGLONG(0);
  clear_has_deletion_date();
}
inline ::google::protobuf::int64 WorkGroupInfo::deletion_date() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.deletion_date)
  return deletion_date_;
}
inline void WorkGroupInfo::set_deletion_date(::google::protobuf::int64 value) {
  set_has_deletion_date();
  deletion_date_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.deletion_date)
}

// optional string creation_date_str = 19;
inline bool WorkGroupInfo::has_creation_date_str() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void WorkGroupInfo::set_has_creation_date_str() {
  _has_bits_[0] |= 0x00004000u;
}
inline void WorkGroupInfo::clear_has_creation_date_str() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void WorkGroupInfo::clear_creation_date_str() {
  if (creation_date_str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creation_date_str_->clear();
  }
  clear_has_creation_date_str();
}
inline const ::std::string& WorkGroupInfo::creation_date_str() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.creation_date_str)
  return *creation_date_str_;
}
inline void WorkGroupInfo::set_creation_date_str(const ::std::string& value) {
  set_has_creation_date_str();
  if (creation_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creation_date_str_ = new ::std::string;
  }
  creation_date_str_->assign(value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.creation_date_str)
}
inline void WorkGroupInfo::set_creation_date_str(const char* value) {
  set_has_creation_date_str();
  if (creation_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creation_date_str_ = new ::std::string;
  }
  creation_date_str_->assign(value);
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupInfo.creation_date_str)
}
inline void WorkGroupInfo::set_creation_date_str(const char* value, size_t size) {
  set_has_creation_date_str();
  if (creation_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creation_date_str_ = new ::std::string;
  }
  creation_date_str_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupInfo.creation_date_str)
}
inline ::std::string* WorkGroupInfo::mutable_creation_date_str() {
  set_has_creation_date_str();
  if (creation_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    creation_date_str_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupInfo.creation_date_str)
  return creation_date_str_;
}
inline ::std::string* WorkGroupInfo::release_creation_date_str() {
  clear_has_creation_date_str();
  if (creation_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = creation_date_str_;
    creation_date_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WorkGroupInfo::set_allocated_creation_date_str(::std::string* creation_date_str) {
  if (creation_date_str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete creation_date_str_;
  }
  if (creation_date_str) {
    set_has_creation_date_str();
    creation_date_str_ = creation_date_str;
  } else {
    clear_has_creation_date_str();
    creation_date_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupInfo.creation_date_str)
}

// optional string deletion_date_str = 20;
inline bool WorkGroupInfo::has_deletion_date_str() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void WorkGroupInfo::set_has_deletion_date_str() {
  _has_bits_[0] |= 0x00008000u;
}
inline void WorkGroupInfo::clear_has_deletion_date_str() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void WorkGroupInfo::clear_deletion_date_str() {
  if (deletion_date_str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    deletion_date_str_->clear();
  }
  clear_has_deletion_date_str();
}
inline const ::std::string& WorkGroupInfo::deletion_date_str() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.deletion_date_str)
  return *deletion_date_str_;
}
inline void WorkGroupInfo::set_deletion_date_str(const ::std::string& value) {
  set_has_deletion_date_str();
  if (deletion_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    deletion_date_str_ = new ::std::string;
  }
  deletion_date_str_->assign(value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.deletion_date_str)
}
inline void WorkGroupInfo::set_deletion_date_str(const char* value) {
  set_has_deletion_date_str();
  if (deletion_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    deletion_date_str_ = new ::std::string;
  }
  deletion_date_str_->assign(value);
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupInfo.deletion_date_str)
}
inline void WorkGroupInfo::set_deletion_date_str(const char* value, size_t size) {
  set_has_deletion_date_str();
  if (deletion_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    deletion_date_str_ = new ::std::string;
  }
  deletion_date_str_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupInfo.deletion_date_str)
}
inline ::std::string* WorkGroupInfo::mutable_deletion_date_str() {
  set_has_deletion_date_str();
  if (deletion_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    deletion_date_str_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupInfo.deletion_date_str)
  return deletion_date_str_;
}
inline ::std::string* WorkGroupInfo::release_deletion_date_str() {
  clear_has_deletion_date_str();
  if (deletion_date_str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = deletion_date_str_;
    deletion_date_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WorkGroupInfo::set_allocated_deletion_date_str(::std::string* deletion_date_str) {
  if (deletion_date_str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete deletion_date_str_;
  }
  if (deletion_date_str) {
    set_has_deletion_date_str();
    deletion_date_str_ = deletion_date_str;
  } else {
    clear_has_deletion_date_str();
    deletion_date_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupInfo.deletion_date_str)
}

// optional bool is_deleted = 23;
inline bool WorkGroupInfo::has_is_deleted() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void WorkGroupInfo::set_has_is_deleted() {
  _has_bits_[0] |= 0x00010000u;
}
inline void WorkGroupInfo::clear_has_is_deleted() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void WorkGroupInfo::clear_is_deleted() {
  is_deleted_ = false;
  clear_has_is_deleted();
}
inline bool WorkGroupInfo::is_deleted() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.is_deleted)
  return is_deleted_;
}
inline void WorkGroupInfo::set_is_deleted(bool value) {
  set_has_is_deleted();
  is_deleted_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.is_deleted)
}

// optional int64 company_id = 24;
inline bool WorkGroupInfo::has_company_id() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void WorkGroupInfo::set_has_company_id() {
  _has_bits_[0] |= 0x00020000u;
}
inline void WorkGroupInfo::clear_has_company_id() {
  _has_bits_[0] &= ~0x00020000u;
}
inline void WorkGroupInfo::clear_company_id() {
  company_id_ = GOOGLE_LONGLONG(0);
  clear_has_company_id();
}
inline ::google::protobuf::int64 WorkGroupInfo::company_id() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.company_id)
  return company_id_;
}
inline void WorkGroupInfo::set_company_id(::google::protobuf::int64 value) {
  set_has_company_id();
  company_id_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.company_id)
}

// optional int32 workgroup_type = 25;
inline bool WorkGroupInfo::has_workgroup_type() const {
  return (_has_bits_[0] & 0x00040000u) != 0;
}
inline void WorkGroupInfo::set_has_workgroup_type() {
  _has_bits_[0] |= 0x00040000u;
}
inline void WorkGroupInfo::clear_has_workgroup_type() {
  _has_bits_[0] &= ~0x00040000u;
}
inline void WorkGroupInfo::clear_workgroup_type() {
  workgroup_type_ = 0;
  clear_has_workgroup_type();
}
inline ::google::protobuf::int32 WorkGroupInfo::workgroup_type() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.workgroup_type)
  return workgroup_type_;
}
inline void WorkGroupInfo::set_workgroup_type(::google::protobuf::int32 value) {
  set_has_workgroup_type();
  workgroup_type_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.workgroup_type)
}

// optional string workgroup_metadata = 26;
inline bool WorkGroupInfo::has_workgroup_metadata() const {
  return (_has_bits_[0] & 0x00080000u) != 0;
}
inline void WorkGroupInfo::set_has_workgroup_metadata() {
  _has_bits_[0] |= 0x00080000u;
}
inline void WorkGroupInfo::clear_has_workgroup_metadata() {
  _has_bits_[0] &= ~0x00080000u;
}
inline void WorkGroupInfo::clear_workgroup_metadata() {
  if (workgroup_metadata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_metadata_->clear();
  }
  clear_has_workgroup_metadata();
}
inline const ::std::string& WorkGroupInfo::workgroup_metadata() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.workgroup_metadata)
  return *workgroup_metadata_;
}
inline void WorkGroupInfo::set_workgroup_metadata(const ::std::string& value) {
  set_has_workgroup_metadata();
  if (workgroup_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_metadata_ = new ::std::string;
  }
  workgroup_metadata_->assign(value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.workgroup_metadata)
}
inline void WorkGroupInfo::set_workgroup_metadata(const char* value) {
  set_has_workgroup_metadata();
  if (workgroup_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_metadata_ = new ::std::string;
  }
  workgroup_metadata_->assign(value);
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupInfo.workgroup_metadata)
}
inline void WorkGroupInfo::set_workgroup_metadata(const char* value, size_t size) {
  set_has_workgroup_metadata();
  if (workgroup_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_metadata_ = new ::std::string;
  }
  workgroup_metadata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupInfo.workgroup_metadata)
}
inline ::std::string* WorkGroupInfo::mutable_workgroup_metadata() {
  set_has_workgroup_metadata();
  if (workgroup_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    workgroup_metadata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupInfo.workgroup_metadata)
  return workgroup_metadata_;
}
inline ::std::string* WorkGroupInfo::release_workgroup_metadata() {
  clear_has_workgroup_metadata();
  if (workgroup_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = workgroup_metadata_;
    workgroup_metadata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WorkGroupInfo::set_allocated_workgroup_metadata(::std::string* workgroup_metadata) {
  if (workgroup_metadata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete workgroup_metadata_;
  }
  if (workgroup_metadata) {
    set_has_workgroup_metadata();
    workgroup_metadata_ = workgroup_metadata;
  } else {
    clear_has_workgroup_metadata();
    workgroup_metadata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupInfo.workgroup_metadata)
}

// optional int64 files_count = 27;
inline bool WorkGroupInfo::has_files_count() const {
  return (_has_bits_[0] & 0x00100000u) != 0;
}
inline void WorkGroupInfo::set_has_files_count() {
  _has_bits_[0] |= 0x00100000u;
}
inline void WorkGroupInfo::clear_has_files_count() {
  _has_bits_[0] &= ~0x00100000u;
}
inline void WorkGroupInfo::clear_files_count() {
  files_count_ = GOOGLE_LONGLONG(0);
  clear_has_files_count();
}
inline ::google::protobuf::int64 WorkGroupInfo::files_count() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupInfo.files_count)
  return files_count_;
}
inline void WorkGroupInfo::set_files_count(::google::protobuf::int64 value) {
  set_has_files_count();
  files_count_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupInfo.files_count)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::rpc::Filter> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::rpc::Filter>() {
  return ::rpc::Filter_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_5fcommon_2eproto__INCLUDED
