// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_common.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "message_common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace rpc {

namespace {

const ::google::protobuf::Descriptor* WorkGroupInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  WorkGroupInfo_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Filter_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_message_5fcommon_2eproto() {
  protobuf_AddDesc_message_5fcommon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "message_common.proto");
  GOOGLE_CHECK(file != NULL);
  WorkGroupInfo_descriptor_ = file->message_type(0);
  static const int WorkGroupInfo_offsets_[21] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, workgroup_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, workgroup_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, description_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, creator_login_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, access_mode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, invite_accepted_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, key_signature_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, key_salt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, encryption_algo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, encryption_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, creation_date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, deletion_date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, creation_date_str_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, deletion_date_str_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, is_deleted_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, company_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, workgroup_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, workgroup_metadata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, files_count_),
  };
  WorkGroupInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      WorkGroupInfo_descriptor_,
      WorkGroupInfo::default_instance_,
      WorkGroupInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorkGroupInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(WorkGroupInfo));
  Filter_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_message_5fcommon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    WorkGroupInfo_descriptor_, &WorkGroupInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_message_5fcommon_2eproto() {
  delete WorkGroupInfo::default_instance_;
  delete WorkGroupInfo_reflection_;
}

void protobuf_AddDesc_message_5fcommon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024message_common.proto\022\003rpc\"\342\003\n\rWorkGrou"
    "pInfo\022\024\n\014workgroup_id\030\001 \001(\003\022\026\n\016workgroup"
    "_name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\025\n\rcrea"
    "tor_login\030\004 \001(\t\022\023\n\013access_mode\030\005 \001(\003\022\027\n\017"
    "invite_accepted\030\010 \001(\010\022\013\n\003key\030\t \001(\t\022\025\n\rke"
    "y_signature\030\n \001(\t\022\020\n\010key_salt\030\013 \001(\t\022\027\n\017e"
    "ncryption_algo\030\014 \001(\005\022\027\n\017encryption_type\030"
    "\r \001(\005\022\014\n\004size\030\020 \001(\003\022\025\n\rcreation_date\030\021 \001"
    "(\003\022\025\n\rdeletion_date\030\022 \001(\003\022\031\n\021creation_da"
    "te_str\030\023 \001(\t\022\031\n\021deletion_date_str\030\024 \001(\t\022"
    "\022\n\nis_deleted\030\027 \001(\010\022\022\n\ncompany_id\030\030 \001(\003\022"
    "\026\n\016workgroup_type\030\031 \001(\005\022\032\n\022workgroup_met"
    "adata\030\032 \001(\t\022\023\n\013files_count\030\033 \001(\003*>\n\006Filt"
    "er\022\021\n\rEXISTING_ONLY\020\000\022\020\n\014DELETED_ONLY\020\001\022"
    "\017\n\013ALL_ENTRIES\020\002B\002H\001", 580);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message_common.proto", &protobuf_RegisterTypes);
  WorkGroupInfo::default_instance_ = new WorkGroupInfo();
  WorkGroupInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_message_5fcommon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5fcommon_2eproto {
  StaticDescriptorInitializer_message_5fcommon_2eproto() {
    protobuf_AddDesc_message_5fcommon_2eproto();
  }
} static_descriptor_initializer_message_5fcommon_2eproto_;
const ::google::protobuf::EnumDescriptor* Filter_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Filter_descriptor_;
}
bool Filter_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int WorkGroupInfo::kWorkgroupIdFieldNumber;
const int WorkGroupInfo::kWorkgroupNameFieldNumber;
const int WorkGroupInfo::kDescriptionFieldNumber;
const int WorkGroupInfo::kCreatorLoginFieldNumber;
const int WorkGroupInfo::kAccessModeFieldNumber;
const int WorkGroupInfo::kInviteAcceptedFieldNumber;
const int WorkGroupInfo::kKeyFieldNumber;
const int WorkGroupInfo::kKeySignatureFieldNumber;
const int WorkGroupInfo::kKeySaltFieldNumber;
const int WorkGroupInfo::kEncryptionAlgoFieldNumber;
const int WorkGroupInfo::kEncryptionTypeFieldNumber;
const int WorkGroupInfo::kSizeFieldNumber;
const int WorkGroupInfo::kCreationDateFieldNumber;
const int WorkGroupInfo::kDeletionDateFieldNumber;
const int WorkGroupInfo::kCreationDateStrFieldNumber;
const int WorkGroupInfo::kDeletionDateStrFieldNumber;
const int WorkGroupInfo::kIsDeletedFieldNumber;
const int WorkGroupInfo::kCompanyIdFieldNumber;
const int WorkGroupInfo::kWorkgroupTypeFieldNumber;
const int WorkGroupInfo::kWorkgroupMetadataFieldNumber;
const int WorkGroupInfo::kFilesCountFieldNumber;
#endif  // !_MSC_VER

WorkGroupInfo::WorkGroupInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:rpc.WorkGroupInfo)
}

void WorkGroupInfo::InitAsDefaultInstance() {
}

WorkGroupInfo::WorkGroupInfo(const WorkGroupInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:rpc.WorkGroupInfo)
}

void WorkGroupInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  workgroup_id_ = GOOGLE_LONGLONG(0);
  workgroup_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  creator_login_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  access_mode_ = GOOGLE_LONGLONG(0);
  invite_accepted_ = false;
  key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_signature_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_salt_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  encryption_algo_ = 0;
  encryption_type_ = 0;
  size_ = GOOGLE_LONGLONG(0);
  creation_date_ = GOOGLE_LONGLONG(0);
  deletion_date_ = GOOGLE_LONGLONG(0);
  creation_date_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deletion_date_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  is_deleted_ = false;
  company_id_ = GOOGLE_LONGLONG(0);
  workgroup_type_ = 0;
  workgroup_metadata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  files_count_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

WorkGroupInfo::~WorkGroupInfo() {
  // @@protoc_insertion_point(destructor:rpc.WorkGroupInfo)
  SharedDtor();
}

void WorkGroupInfo::SharedDtor() {
  if (workgroup_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete workgroup_name_;
  }
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete description_;
  }
  if (creator_login_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete creator_login_;
  }
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_;
  }
  if (key_signature_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_signature_;
  }
  if (key_salt_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_salt_;
  }
  if (creation_date_str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete creation_date_str_;
  }
  if (deletion_date_str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete deletion_date_str_;
  }
  if (workgroup_metadata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete workgroup_metadata_;
  }
  if (this != default_instance_) {
  }
}

void WorkGroupInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WorkGroupInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return WorkGroupInfo_descriptor_;
}

const WorkGroupInfo& WorkGroupInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_5fcommon_2eproto();
  return *default_instance_;
}

WorkGroupInfo* WorkGroupInfo::default_instance_ = NULL;

WorkGroupInfo* WorkGroupInfo::New() const {
  return new WorkGroupInfo;
}

void WorkGroupInfo::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<WorkGroupInfo*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    workgroup_id_ = GOOGLE_LONGLONG(0);
    if (has_workgroup_name()) {
      if (workgroup_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        workgroup_name_->clear();
      }
    }
    if (has_description()) {
      if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        description_->clear();
      }
    }
    if (has_creator_login()) {
      if (creator_login_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        creator_login_->clear();
      }
    }
    access_mode_ = GOOGLE_LONGLONG(0);
    invite_accepted_ = false;
    if (has_key()) {
      if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        key_->clear();
      }
    }
    if (has_key_signature()) {
      if (key_signature_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        key_signature_->clear();
      }
    }
  }
  if (_has_bits_[8 / 32] & 65280) {
    ZR_(encryption_algo_, deletion_date_);
    if (has_key_salt()) {
      if (key_salt_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        key_salt_->clear();
      }
    }
    if (has_creation_date_str()) {
      if (creation_date_str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        creation_date_str_->clear();
      }
    }
    if (has_deletion_date_str()) {
      if (deletion_date_str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        deletion_date_str_->clear();
      }
    }
  }
  if (_has_bits_[16 / 32] & 2031616) {
    ZR_(is_deleted_, workgroup_type_);
    company_id_ = GOOGLE_LONGLONG(0);
    if (has_workgroup_metadata()) {
      if (workgroup_metadata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        workgroup_metadata_->clear();
      }
    }
    files_count_ = GOOGLE_LONGLONG(0);
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool WorkGroupInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:rpc.WorkGroupInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 workgroup_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &workgroup_id_)));
          set_has_workgroup_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_workgroup_name;
        break;
      }

      // optional string workgroup_name = 2;
      case 2: {
        if (tag == 18) {
         parse_workgroup_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_workgroup_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->workgroup_name().data(), this->workgroup_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "workgroup_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_description;
        break;
      }

      // optional string description = 3;
      case 3: {
        if (tag == 26) {
         parse_description:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->description().data(), this->description().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "description");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_creator_login;
        break;
      }

      // optional string creator_login = 4;
      case 4: {
        if (tag == 34) {
         parse_creator_login:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_creator_login()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->creator_login().data(), this->creator_login().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "creator_login");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_access_mode;
        break;
      }

      // optional int64 access_mode = 5;
      case 5: {
        if (tag == 40) {
         parse_access_mode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &access_mode_)));
          set_has_access_mode();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_invite_accepted;
        break;
      }

      // optional bool invite_accepted = 8;
      case 8: {
        if (tag == 64) {
         parse_invite_accepted:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &invite_accepted_)));
          set_has_invite_accepted();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_key;
        break;
      }

      // optional string key = 9;
      case 9: {
        if (tag == 74) {
         parse_key:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "key");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_key_signature;
        break;
      }

      // optional string key_signature = 10;
      case 10: {
        if (tag == 82) {
         parse_key_signature:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key_signature()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->key_signature().data(), this->key_signature().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "key_signature");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_key_salt;
        break;
      }

      // optional string key_salt = 11;
      case 11: {
        if (tag == 90) {
         parse_key_salt:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key_salt()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->key_salt().data(), this->key_salt().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "key_salt");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_encryption_algo;
        break;
      }

      // optional int32 encryption_algo = 12;
      case 12: {
        if (tag == 96) {
         parse_encryption_algo:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &encryption_algo_)));
          set_has_encryption_algo();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(104)) goto parse_encryption_type;
        break;
      }

      // optional int32 encryption_type = 13;
      case 13: {
        if (tag == 104) {
         parse_encryption_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &encryption_type_)));
          set_has_encryption_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(128)) goto parse_size;
        break;
      }

      // optional int64 size = 16;
      case 16: {
        if (tag == 128) {
         parse_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &size_)));
          set_has_size();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(136)) goto parse_creation_date;
        break;
      }

      // optional int64 creation_date = 17;
      case 17: {
        if (tag == 136) {
         parse_creation_date:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &creation_date_)));
          set_has_creation_date();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(144)) goto parse_deletion_date;
        break;
      }

      // optional int64 deletion_date = 18;
      case 18: {
        if (tag == 144) {
         parse_deletion_date:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &deletion_date_)));
          set_has_deletion_date();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(154)) goto parse_creation_date_str;
        break;
      }

      // optional string creation_date_str = 19;
      case 19: {
        if (tag == 154) {
         parse_creation_date_str:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_creation_date_str()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->creation_date_str().data(), this->creation_date_str().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "creation_date_str");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(162)) goto parse_deletion_date_str;
        break;
      }

      // optional string deletion_date_str = 20;
      case 20: {
        if (tag == 162) {
         parse_deletion_date_str:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deletion_date_str()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->deletion_date_str().data(), this->deletion_date_str().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "deletion_date_str");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(184)) goto parse_is_deleted;
        break;
      }

      // optional bool is_deleted = 23;
      case 23: {
        if (tag == 184) {
         parse_is_deleted:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_deleted_)));
          set_has_is_deleted();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(192)) goto parse_company_id;
        break;
      }

      // optional int64 company_id = 24;
      case 24: {
        if (tag == 192) {
         parse_company_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &company_id_)));
          set_has_company_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(200)) goto parse_workgroup_type;
        break;
      }

      // optional int32 workgroup_type = 25;
      case 25: {
        if (tag == 200) {
         parse_workgroup_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &workgroup_type_)));
          set_has_workgroup_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(210)) goto parse_workgroup_metadata;
        break;
      }

      // optional string workgroup_metadata = 26;
      case 26: {
        if (tag == 210) {
         parse_workgroup_metadata:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_workgroup_metadata()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->workgroup_metadata().data(), this->workgroup_metadata().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "workgroup_metadata");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(216)) goto parse_files_count;
        break;
      }

      // optional int64 files_count = 27;
      case 27: {
        if (tag == 216) {
         parse_files_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &files_count_)));
          set_has_files_count();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:rpc.WorkGroupInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:rpc.WorkGroupInfo)
  return false;
#undef DO_
}

void WorkGroupInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:rpc.WorkGroupInfo)
  // optional int64 workgroup_id = 1;
  if (has_workgroup_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->workgroup_id(), output);
  }

  // optional string workgroup_name = 2;
  if (has_workgroup_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->workgroup_name().data(), this->workgroup_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "workgroup_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->workgroup_name(), output);
  }

  // optional string description = 3;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->description(), output);
  }

  // optional string creator_login = 4;
  if (has_creator_login()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->creator_login().data(), this->creator_login().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "creator_login");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->creator_login(), output);
  }

  // optional int64 access_mode = 5;
  if (has_access_mode()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->access_mode(), output);
  }

  // optional bool invite_accepted = 8;
  if (has_invite_accepted()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->invite_accepted(), output);
  }

  // optional string key = 9;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->key(), output);
  }

  // optional string key_signature = 10;
  if (has_key_signature()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key_signature().data(), this->key_signature().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key_signature");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->key_signature(), output);
  }

  // optional string key_salt = 11;
  if (has_key_salt()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key_salt().data(), this->key_salt().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key_salt");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->key_salt(), output);
  }

  // optional int32 encryption_algo = 12;
  if (has_encryption_algo()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->encryption_algo(), output);
  }

  // optional int32 encryption_type = 13;
  if (has_encryption_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(13, this->encryption_type(), output);
  }

  // optional int64 size = 16;
  if (has_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(16, this->size(), output);
  }

  // optional int64 creation_date = 17;
  if (has_creation_date()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(17, this->creation_date(), output);
  }

  // optional int64 deletion_date = 18;
  if (has_deletion_date()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(18, this->deletion_date(), output);
  }

  // optional string creation_date_str = 19;
  if (has_creation_date_str()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->creation_date_str().data(), this->creation_date_str().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "creation_date_str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      19, this->creation_date_str(), output);
  }

  // optional string deletion_date_str = 20;
  if (has_deletion_date_str()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->deletion_date_str().data(), this->deletion_date_str().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "deletion_date_str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      20, this->deletion_date_str(), output);
  }

  // optional bool is_deleted = 23;
  if (has_is_deleted()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(23, this->is_deleted(), output);
  }

  // optional int64 company_id = 24;
  if (has_company_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(24, this->company_id(), output);
  }

  // optional int32 workgroup_type = 25;
  if (has_workgroup_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(25, this->workgroup_type(), output);
  }

  // optional string workgroup_metadata = 26;
  if (has_workgroup_metadata()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->workgroup_metadata().data(), this->workgroup_metadata().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "workgroup_metadata");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      26, this->workgroup_metadata(), output);
  }

  // optional int64 files_count = 27;
  if (has_files_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(27, this->files_count(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:rpc.WorkGroupInfo)
}

::google::protobuf::uint8* WorkGroupInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc.WorkGroupInfo)
  // optional int64 workgroup_id = 1;
  if (has_workgroup_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->workgroup_id(), target);
  }

  // optional string workgroup_name = 2;
  if (has_workgroup_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->workgroup_name().data(), this->workgroup_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "workgroup_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->workgroup_name(), target);
  }

  // optional string description = 3;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->description(), target);
  }

  // optional string creator_login = 4;
  if (has_creator_login()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->creator_login().data(), this->creator_login().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "creator_login");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->creator_login(), target);
  }

  // optional int64 access_mode = 5;
  if (has_access_mode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->access_mode(), target);
  }

  // optional bool invite_accepted = 8;
  if (has_invite_accepted()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->invite_accepted(), target);
  }

  // optional string key = 9;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->key(), target);
  }

  // optional string key_signature = 10;
  if (has_key_signature()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key_signature().data(), this->key_signature().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key_signature");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->key_signature(), target);
  }

  // optional string key_salt = 11;
  if (has_key_salt()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key_salt().data(), this->key_salt().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key_salt");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->key_salt(), target);
  }

  // optional int32 encryption_algo = 12;
  if (has_encryption_algo()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->encryption_algo(), target);
  }

  // optional int32 encryption_type = 13;
  if (has_encryption_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(13, this->encryption_type(), target);
  }

  // optional int64 size = 16;
  if (has_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(16, this->size(), target);
  }

  // optional int64 creation_date = 17;
  if (has_creation_date()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(17, this->creation_date(), target);
  }

  // optional int64 deletion_date = 18;
  if (has_deletion_date()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(18, this->deletion_date(), target);
  }

  // optional string creation_date_str = 19;
  if (has_creation_date_str()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->creation_date_str().data(), this->creation_date_str().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "creation_date_str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        19, this->creation_date_str(), target);
  }

  // optional string deletion_date_str = 20;
  if (has_deletion_date_str()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->deletion_date_str().data(), this->deletion_date_str().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "deletion_date_str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        20, this->deletion_date_str(), target);
  }

  // optional bool is_deleted = 23;
  if (has_is_deleted()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(23, this->is_deleted(), target);
  }

  // optional int64 company_id = 24;
  if (has_company_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(24, this->company_id(), target);
  }

  // optional int32 workgroup_type = 25;
  if (has_workgroup_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(25, this->workgroup_type(), target);
  }

  // optional string workgroup_metadata = 26;
  if (has_workgroup_metadata()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->workgroup_metadata().data(), this->workgroup_metadata().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "workgroup_metadata");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        26, this->workgroup_metadata(), target);
  }

  // optional int64 files_count = 27;
  if (has_files_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(27, this->files_count(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc.WorkGroupInfo)
  return target;
}

int WorkGroupInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int64 workgroup_id = 1;
    if (has_workgroup_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->workgroup_id());
    }

    // optional string workgroup_name = 2;
    if (has_workgroup_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->workgroup_name());
    }

    // optional string description = 3;
    if (has_description()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->description());
    }

    // optional string creator_login = 4;
    if (has_creator_login()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->creator_login());
    }

    // optional int64 access_mode = 5;
    if (has_access_mode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->access_mode());
    }

    // optional bool invite_accepted = 8;
    if (has_invite_accepted()) {
      total_size += 1 + 1;
    }

    // optional string key = 9;
    if (has_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->key());
    }

    // optional string key_signature = 10;
    if (has_key_signature()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->key_signature());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional string key_salt = 11;
    if (has_key_salt()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->key_salt());
    }

    // optional int32 encryption_algo = 12;
    if (has_encryption_algo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->encryption_algo());
    }

    // optional int32 encryption_type = 13;
    if (has_encryption_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->encryption_type());
    }

    // optional int64 size = 16;
    if (has_size()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->size());
    }

    // optional int64 creation_date = 17;
    if (has_creation_date()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->creation_date());
    }

    // optional int64 deletion_date = 18;
    if (has_deletion_date()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->deletion_date());
    }

    // optional string creation_date_str = 19;
    if (has_creation_date_str()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->creation_date_str());
    }

    // optional string deletion_date_str = 20;
    if (has_deletion_date_str()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->deletion_date_str());
    }

  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    // optional bool is_deleted = 23;
    if (has_is_deleted()) {
      total_size += 2 + 1;
    }

    // optional int64 company_id = 24;
    if (has_company_id()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->company_id());
    }

    // optional int32 workgroup_type = 25;
    if (has_workgroup_type()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->workgroup_type());
    }

    // optional string workgroup_metadata = 26;
    if (has_workgroup_metadata()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->workgroup_metadata());
    }

    // optional int64 files_count = 27;
    if (has_files_count()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->files_count());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WorkGroupInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const WorkGroupInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const WorkGroupInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void WorkGroupInfo::MergeFrom(const WorkGroupInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_workgroup_id()) {
      set_workgroup_id(from.workgroup_id());
    }
    if (from.has_workgroup_name()) {
      set_workgroup_name(from.workgroup_name());
    }
    if (from.has_description()) {
      set_description(from.description());
    }
    if (from.has_creator_login()) {
      set_creator_login(from.creator_login());
    }
    if (from.has_access_mode()) {
      set_access_mode(from.access_mode());
    }
    if (from.has_invite_accepted()) {
      set_invite_accepted(from.invite_accepted());
    }
    if (from.has_key()) {
      set_key(from.key());
    }
    if (from.has_key_signature()) {
      set_key_signature(from.key_signature());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_key_salt()) {
      set_key_salt(from.key_salt());
    }
    if (from.has_encryption_algo()) {
      set_encryption_algo(from.encryption_algo());
    }
    if (from.has_encryption_type()) {
      set_encryption_type(from.encryption_type());
    }
    if (from.has_size()) {
      set_size(from.size());
    }
    if (from.has_creation_date()) {
      set_creation_date(from.creation_date());
    }
    if (from.has_deletion_date()) {
      set_deletion_date(from.deletion_date());
    }
    if (from.has_creation_date_str()) {
      set_creation_date_str(from.creation_date_str());
    }
    if (from.has_deletion_date_str()) {
      set_deletion_date_str(from.deletion_date_str());
    }
  }
  if (from._has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (from.has_is_deleted()) {
      set_is_deleted(from.is_deleted());
    }
    if (from.has_company_id()) {
      set_company_id(from.company_id());
    }
    if (from.has_workgroup_type()) {
      set_workgroup_type(from.workgroup_type());
    }
    if (from.has_workgroup_metadata()) {
      set_workgroup_metadata(from.workgroup_metadata());
    }
    if (from.has_files_count()) {
      set_files_count(from.files_count());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void WorkGroupInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WorkGroupInfo::CopyFrom(const WorkGroupInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WorkGroupInfo::IsInitialized() const {

  return true;
}

void WorkGroupInfo::Swap(WorkGroupInfo* other) {
  if (other != this) {
    std::swap(workgroup_id_, other->workgroup_id_);
    std::swap(workgroup_name_, other->workgroup_name_);
    std::swap(description_, other->description_);
    std::swap(creator_login_, other->creator_login_);
    std::swap(access_mode_, other->access_mode_);
    std::swap(invite_accepted_, other->invite_accepted_);
    std::swap(key_, other->key_);
    std::swap(key_signature_, other->key_signature_);
    std::swap(key_salt_, other->key_salt_);
    std::swap(encryption_algo_, other->encryption_algo_);
    std::swap(encryption_type_, other->encryption_type_);
    std::swap(size_, other->size_);
    std::swap(creation_date_, other->creation_date_);
    std::swap(deletion_date_, other->deletion_date_);
    std::swap(creation_date_str_, other->creation_date_str_);
    std::swap(deletion_date_str_, other->deletion_date_str_);
    std::swap(is_deleted_, other->is_deleted_);
    std::swap(company_id_, other->company_id_);
    std::swap(workgroup_type_, other->workgroup_type_);
    std::swap(workgroup_metadata_, other->workgroup_metadata_);
    std::swap(files_count_, other->files_count_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata WorkGroupInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = WorkGroupInfo_descriptor_;
  metadata.reflection = WorkGroupInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc

// @@protoc_insertion_point(global_scope)
